### ISSUE TITLE
Java Exception when installing already downloaded apk

### ISSUE THREAD

**Issue by matze19999** [YTVanced/VancedInstaller#17]
![Screenshot_20200530-122739](https://user-images.githubusercontent.com/13684520/83326001-1412c500-a271-11ea-815b-608a832f2990.jpg)

Like u see in the screenshot, I get an error message if I hit the install button for microg if the apk was already downloaded.

**Comment by X1nto** [comment]
Hi, thanks for your feedback. The error only occurs if you're trying to download file while it's already being downloaded (not when it is downloaded). We'll adress this issue in the next update

**Comment by matze19999** [comment]
Good to know, thanks!

Keep up the good work :)
