### ISSUE TITLE
Error when installing with SAI

### ISSUE THREAD

**Issue by bertek41** [YTVanced/VancedInstaller#19]
INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113

**Comment by X1nto** [comment]
Why are you reporting it here

**Comment by bertek41** [comment]
Because its happened when i was trying to install Vanced

**Comment by X1nto** [comment]
This is not a right place for that

**Comment by bertek41** [comment]
Where to i can report this?

**Comment by X1nto** [comment]
Just download legacy vanced version from vanced.app and install it with sai

**Comment by bertek41** [comment]
Thats what i did and when installing SAI gives me this error

**Comment by X1nto** [comment]
You clearly downloaded default. Now if you'll excuse me, I have to finish manager

**Comment by bertek41** [comment]
Yeah you're right thanks.
