### ISSUE TITLE
Crash when choosing dark mode

### ISSUE THREAD

**Issue by pooyashahidi** [YTVanced/VancedInstaller#21]
First, I'm in the category (minority) that find installing split apks easy even on miui :D
But i just wanted to try this out so here is the error i get when choosing dark mode in the vanced manager settings:

![Screenshot_2020-06-23-03-06-12-913_com miui bugreport](https://user-images.githubusercontent.com/5418119/85349640-4d9cc000-b4ff-11ea-83ce-72e44ba9090c.jpg)

Tested on android 10, miui 12. Feel free to ignore/close if you don't like Miui or believe everything is their fault (judging by the readme) :D

**Comment by X1nto** [comment]
Hi. The issue is with us using Material Design components instead of AppCompat, we're looking into solutions and final product should fix this. Thanks for being interested
